---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter-service
  name: greeter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-service
  template:
    metadata:
      labels:
        app: greeter-service
    spec:
      containers:
        - name: app
          image: ghcr.io/gitops-ci-cd/greeter-service:205e9b3dba5365cfb44db168521a4146da2f3d06
          env:
            - name: PORT
              value: "50051"
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
