---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: app
          image: ghcr.io/gitops-ci-cd/greeter:17889c7a33dc027e34bcfe5949d531825567ceb5
          env:
            - name: PORT
              value: "50051"
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
