---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: greeter-service-route
spec:
  parentRefs:
    - name: greeter-service
      kind: Service
      group: core
  hostnames:
    - "greeter-service.localhost"
  rules:
    - matches:
        - method:
            service: com.acme.schema.v1.GreeterService
            type: Exact
      backendRefs:
        - group: ''
          kind: Service
          name: greeter-service
          port: 50051
          weight: 1
